backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    identifier_field : pageUrl
    slug: "{{pageUrl}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Page URL", name: "pageUrl", widget: "string", pattern: ['^[a-z0-9 ]+$', "No uppercase allowed"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Modify Date", name: "modifyDate", widget: "datetime"}
      - {label: "Excerpt", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Facebook Image", name: "facebookImage", widget: image}
      - {label: "Twitter Image", name: "twitterImage", widget: image}
      - {label: "Pinterest Image", name: "pinterestImage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Main Tag", name: "mainTag", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "elementor"
    label: "Elementor"
    folder: "src/pages/elementor"
    create: true
    identifier_field : pageUrl
    slug: "{{pageUrl}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Page URL", name: "pageUrl", widget: "string", pattern: ['^[a-z0-9 ]+$', "No uppercase allowed"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Modify Date", name: "modifyDate", widget: "datetime"}
      - {label: "Excerpt", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Facebook Image", name: "facebookImage", widget: image}
      - {label: "Twitter Image", name: "twitterImage", widget: image}
      - {label: "Pinterest Image", name: "pinterestImage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Main Tag", name: "mainTag", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}